### PR TITLE
feat(prompts): you can now change your image as well as your client settings

### PR DESCRIPTION
**Pull request by chikof**
I only added utility to the "yes" or "no" options.

### CODE REVIEW

**Comment by chirag-droid** [comment]
you could do that previously as well?

**Comment by chikof** [comment]
nope

**Comment by chirag-droid** [comment]
it will create a new config if the user is not configured, or the user says yes. if the user says no it will return early

**Comment by chirag-droid** [comment]
nvm, I am so dumb. merged 👍 thanks

**Pull request merged**
